### ISSUE TITLE
Issues about the localization-stability calculation

### ISSUE THREAD

**Issue by MoleImg** [JappaB/Active_Learning_Object_Detection#1]
Hi Jasper,

I have read your thesis and it is really an impressive work. Recently I want to re-run your code and I got some problems here:
1.I want to use the localization-stability for the uncertainty quantification. I know it's from a referenced paper but they didn't release their own implementation for public. I saw your implementation in this repo, but I cannot understand the code when you rearrange the reference boxes and the "noisy boxes" corresponding to each level of noise.
In detail, in Line 694 of active_learning_helpers.py, after you get the output of the SSD model:
```
# use the nonzero boxes for each class
reference_boxes = torch.cat([reference_output[0][:,cl,:int(reference_output[1][cl].item()),:].squeeze(dim=0) for cl in range(1,args.num_classes)])
```
I cannot understand what this line is doing and it will cause exception and get crash. The similar processing also appears for the "noisy boxes" in Line 702 of active_learning_helpers.py:
```
noisy_boxes = torch.cat([im_preds[noisy_preds_idx][0][:, cl, :int(im_preds[noisy_preds_idx][1][cl].item()), :].squeeze(dim=0) for cl in range(1, args.num_classes)])
```
So could you please explain this for me and solve my confusion? I really appreciate it. Thank you so much

**Comment by JappaB** [comment]
Hi there @MoleImg,
My apologies for the extremely late reply. I've been focussed on other things for quite some time.
I assume you are not in need of an answer anymore, but in any case will give a short reply.
It's been a long time since I wrote the code, but I do remember that even though I had contact with the original authors of the localization-stability paper, I wasn't able to reproduce their results. My implementation of their code typically resulted in worse than random sampling. My thesis prof therefore advised to not include them in the comparison, as the paper also wasn't published in a big reputable venue.

I don't have a working sample of the code currently so in terms of debugging I cannot help you.
